.TH BJC 1 "" "" "BJC 1.0"
.SH NAME
BJC \- Better Java Compile
.SH SYNOPSIS
.B BJC
.RB [ \-l
.IR directory ]
.RB [ \-v ]
.RB [ \-q ]
.RB [ \-d
.IR directory ]
.RB [ \-j
.IR options ]
.RB [ \-x
.IR class ]
.RB [ \-s ]
.RB [ \-t ]
.RB [ \--jar
.IR manifest ]

BJC
.RB \-h

.SH DESCRIPTION
BJC allowes you to compile whole Java Projects from the top folder without the use of any IDE etc. It is just a simple application that you just run and it compiles the whole folderstructure for you from bottom to top in the right order.

.SH OPTIONS

.TP
\fB\-l\fR, \fB\-\-libdir\fR \fI\,DIRECTORY\/\fR
Lets you choose another directory for jar-librarys than the default ./.libs It only works with relative paths compared to the
.BR --directory

.TP
\fB\-v\fR, \fB\-\-verbose\fR
Activates verbose mode, only usefull when you set it to false in the sourcecode

.TP
\fB\-q\fR, \fB\-\-quiet\fR
Basicly the opposite of
.BR --verbose
, it turns of any messages except javac errors!

.TP
\fB\-d\fR, \fB\-\-directory\fR \fI\,DIRECTORY\/\fR
Changes the top-level directory of the program, so you can use it while being in e.g. a subdirectory. Works with both relative and absolute paths.

.TP
\fB\-j\fR, \fB\-\-javacOptions\fR \fI\,ARGS\/\fR
Allows you to add custom javac options, this inclues every option except
.BR --classpath
since that one has to be set by BJC

.TP
\fB\-x\fR, \fB\-\-execute\fR \fI\,CLASS\/\fR
Allows you to execute the
.BR CLASS
after compilation and opens a terminal for any terminal output, unless
.BR --silent
is specified

.TP
\fB\-s\fR, \fB\-\-silent\fR
Prevents
.BR --execute
from opening a terminal for the execution

.TP
\fB\-t\fR, \fB-\-terminal\fR
Spawns a terminal on execution, even if
.BR --silent
was specified earlier

.TP
\fB\-\-jar\fR \fI\,MANIFEST\/\fR
Allows you to build a jar file from the files it compiles and the given MANIFEST file


.TP
\fB\-h\fR, \fB\-\-help\fR
Shows a small help page with a short description of all options

.SH AUTHOR
Written by Annie Herrmann(annieherrmann03@gmail.com)

.SH REPORTING BUGS
Please report any bug you can find to either the github page or to my email!

.SH LICENSE
See the LICENSE file, if you deleted the git clone after the installation, go to my github for it!

.SH SEE ALSO
.BR javac (1),
.BR java (1),
.BR ruby (1)
